[package]
name = "grafted-frameworks"
description = "Darwin framework shims - CoreFoundation, Foundation, CoreGraphics, AppKit, UIKit, Metal"
version.workspace = true
edition.workspace = true

[dependencies]
grafted-objc.workspace = true
goblin.workspace = true
thiserror.workspace = true
log.workspace = true
libc = "0.2"
